docker_build(
  'gateway',
  context = '.',
  only = ['krakend.json']
)

k8s_yaml('../.k8s/gateway.yaml')

k8s_resource(
  'gateway',
  port_forwards = 3000,
  labels = ['gateway'],
  resource_deps=[
    'gateway-istio', 
    'default-namespace', 
    'coredns-config'
  ],
)
