name: Affiliate Staging
run-name: Affiliate Staging

on:
  push:
    branches:
      - main

jobs:

  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit

  deploy:
    if: contains(needs.build.outputs.changed, 'true')
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
    
      - name: Deploy
        shell: bash
        run: |
          helm upgrade --install affiliate \
          --namespace default \
          --set services.backend.image.tag="${{ needs.build.outputs.version }}" ./helm-charts